pipeline {
  agent any

  stages {

    stage('Info') {
      steps {
        sh 'echo "Job: $JOB_NAME"'
        sh 'echo "Build: $BUILD_NUMBER"'
      }
    }

    stage('Lint') {
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
        }
      }
      steps {
        sh 'make lint'
      }
    }

    stage('Test') {
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
        }
      }
      steps {
        sh 'make test'
      }
    }
  }
}

